Data input dialog
smilenow24/capstone-project pull request #5
Opened 2022-06-28 12:30 UTC by smilenow24

2022-06-29 14:19 UTC, ahohnsen requested changes
Hey Kim,

Great work! I have a few suggestions, please take a look at my comments :)

2022-06-29 14:19 UTC, ahohnsen commented on src/App.js
> +  let formattedActualDate = actualDate.toLocaleDateString()
If possible, you should use `const` instead of `let`. If I am seeing it correctly you do not assign another value to this variables later on, so you could use `const` here.

```suggestion
  const actualDate = new Date();
  const formattedActualDate = actualDate.toLocaleDateString()
```

2022-06-29 14:19 UTC, ahohnsen commented on src/App.js
> +    <H1>Energy-Budget-App</H1>
I personally would avoid naming your styled components exactly like existing html tags as this might lead to confusion. Maybe you can rename it to "Headline", "MainHeading" etc.

2022-06-29 14:19 UTC, ahohnsen commented on src/App.js
> +          </li>
I think that you do not need the `span` here. You can show the date directly in your `li` element.

```suggestion
          <li key={id}> {date}  {value} kw</li>
```

2022-06-29 14:19 UTC, ahohnsen commented on src/App.js
> +      <section><p>{formattedActualDate}</p></section>
Instead of a `p`-tag, it would also be possible to use a `h2` as the actual date seems to be very present in your scribble. As you like :)

2022-06-29 14:19 UTC, ahohnsen commented on src/App.js
> +      <InputDataDialog setInputs={setInputs} inputs={inputs} />
Passing down `setState` is not a good practice. I would suggest to pass down a function which takes care of updating the state (maybe you could call it "addInput" or something like that).

2022-06-29 14:19 UTC, ahohnsen commented on src/components/InputDataDialog.js
> +export default function InputDataDialog({setInputs, inputs}) {
Same as above - better do not pass down the `setState`

2022-06-29 14:19 UTC, ahohnsen commented on src/components/InputDataDialog.js
> +        setInputs([newInput, ...inputs]);
Here you can call the function which you pass down from the `App.js` to update your state :) instead of calling `setInputs`

2022-06-29 14:19 UTC, ahohnsen commented on src/components/InputDataDialog.spec.js
> +    it('is an accessible form', () => {
For your tests, please have a look at the tests Stefan showed you :) 
Additionally, as your input field is required, I would also test that.

2022-06-29 14:19 UTC, ahohnsen commented on src/components/InputDataDialog.stories.js
> +    argTypes: {setInputs: {action: 'setInputs'}},
If you update your code, please do not forget to update the function here as well :)

2022-06-30 08:46 UTC, stefankorder approved these changes
👍🏻

2022-06-30 09:01 UTC, merged